apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: binpackschedulers.binpack.k8s.io
  annotations:
    api-approved.kubernetes.io: "https://github.com/kubernetes/enhancements/pull/1111"
spec:
  group: binpack.k8s.io
  names:
    kind: BinpackScheduler
    listKind: BinpackSchedulerList
    plural: binpackschedulers
    singular: binpackscheduler
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                nodeSelector:
                  type: string
