apiVersion: v1
kind: ServiceAccount
metadata:
  name: binpack-operator-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: binpack-operator-role
rules:
  # binpackschedulers 리소스에 대한 권한 부여
  - apiGroups: ["binpack.k8s.io"]
    resources: ["binpackschedulers"]
    verbs: ["get", "list", "watch"]
  # 커스텀 리소스 정의(CRD)에 대한 권한 부여
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
  # operator가 다른 리소스(예: nodes, deployments 등)에 접근해야 한다면 추가 권한을 명시합니다.
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: binpack-operator-binding
subjects:
  - kind: ServiceAccount
    name: binpack-operator-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: binpack-operator-role
  apiGroup: rbac.authorization.k8s.io
